---
title: imran
author:
  email: imran@therashids.com
  github: squito
  name: "Imran Rashid"

auto: false
safe: false
server: false
server_port: 4000
base-url: /
production_url: "http://squito.github.com"

source: .
destination: ./_site
plugins: ./_plugins
exclude:
  - README.md
  - util
  - drafts
  - config
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - vendor
  - config.ru
  - unicorn.rb
  - fabfile.py

future: true
lsi: false
pygments: true
markdown: rdiscount
permalink: "/posts/:title"

rdiscount:
  extensions:
    - smart
